### PR TITLE
don't play notes automatically on learning mode

### PR DESCRIPTION
**Pull request by albfan**
On learning mode only notes played by you should sound
Be played automatically is distracting and confusing.

### CODE REVIEW

**Comment by arcusfelis** [comment]
There's "learning silently" mode, it's what are you asking. We use user's input to play in this case. 
Also, I think the current learning mode is useful: you can hear sound before you play it. It's disturbing when playing fast, but useful for hard songs.
I would suggest to rename the current mode into something like "hear before play". We can delete it later.

I can check this PR after January 10, because I am being away from my midi-keyboard.

On January 5, 2015 4:28:44 AM CET, Alberto Fanjul <notifications@github.com> wrote:
>On learning mode only notes played by you should sound
>Be played automatically is distracting and confusing.
>You can merge this Pull Request by running:
>
>  git pull https://github.com/albfan/linthesia master
>
>Or you can view, comment on it, or merge it online at:
>
>  https://github.com/arcusfelis/linthesia/pull/1
>
>-- Commit Summary --
>
>  * remove generated autotools files
>  * fix when playing outside KDE
>  * avoid learning mode from play my notes
>  * remove unused variable
>
>-- File Changes --
>
>    D config.guess (1552)
>    D config.sub (1806)
>    D m4/libtool.m4 (7995)
>    D m4/ltoptions.m4 (384)
>    D m4/ltsugar.m4 (123)
>    D m4/ltversion.m4 (23)
>    D m4/lt~obsolete.m4 (98)
>    D missing (215)
>    M scripts/delay_screensaver.sh (4)
>    M src/PlayingState.cpp (5)
>
>-- Patch Links --
>
>https://github.com/arcusfelis/linthesia/pull/1.patch
>https://github.com/arcusfelis/linthesia/pull/1.diff
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/arcusfelis/linthesia/pull/1

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by albfan** [comment]
Problem with silent modes is they are totally silent, and I want to taste what I'm playing.

I'm agree It helps you to feel the tempo from a song. That "learning guided" mode makes sense for intermediate users, so let's add it and see what happens.

There's too another mode where you can hear all the bad notes you play to understand why they don't sound right or even to add flourishes to the song, although you get bad scores.

I will work on them and tell you something

**Comment by arcusfelis** [comment]
So, basically your change is already implemented with ModeLearningSilently.
Probably, we should have better naming.

**Comment by albfan** [comment]
Yes, I have notice that about scores. It shouldn't add score when playing note after a stop.

**Comment by arcusfelis** [comment]
ok,  I see 

On January 18, 2015 9:53:50 AM CET, Alberto Fanjul <notifications@github.com> wrote:
>Yes, I have notice that about scores. It shouldn't add score when
>playing note after a stop.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/arcusfelis/linthesia/pull/1#issuecomment-70400905

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by arcusfelis** [comment]
Is there a way to generate m4 directory?

**Comment by arcusfelis** [comment]
I cherry-picked last three commits:
- Alberto Fanjul 	fix when playing outside KDE 	
- Alberto Fanjul 	avoid learning mode from play my notes 	
- Alberto Fanjul 	remove unused variable

One more thing: it would be great to have all commits starting with a title letter :)

**Comment by albfan** [comment]
About m4: Issuing `autreconf -ivf` should call appropriate commands in appropriate order

About capitalization, let me rebase commits to rework messages, that's an easy clean up

**Comment by arcusfelis** [comment]
Thank you.
I reset my changes and waiting for the rebase.

On Mon, Jan 19, 2015 at 5:30 AM, Alberto Fanjul <notifications@github.com>
wrote:

> About m4: Issuing autreconf -ivf should call appropriate commands in
> appropriate order
>
> About capitalization, let me rebase commits to rework messages, that's an
> easy clean up
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arcusfelis/linthesia/pull/1#issuecomment-70445326>.
>



-- 
С уважением,
Уваров Михаил.
Best regards,
Uvarov Michael

**Comment by albfan** [comment]
Here you are. 

Let me know any doubts about "Remove generated autotools files", 

Those files are scary for newcomers. That's the only purpose of remove them.

**Comment by arcusfelis** [comment]
I know. We should add this `autreconf -ivf` as a part of README.

**Comment by arcusfelis** [comment]
Merged.
Another thing about pull requests and team work:
- I usually make a separate branch for each idea/feature;
- The master branch contains version that works (i.e. upstream, but not stable version).
It makes code easier to merge, because each branch can be merged as soon as it's ready. We should also keep master branch in sync as a basic branch for rebasing. These feature branches can be deleted as soon as they are merged.

PS: I put two commits on top for handling dynamic usb devices. The code is not the best, but it works.
Next time I will use proper branching.

**Comment by albfan** [comment]
Sounds great. I will apply for next features.

2015-01-19 23:50 GMT+01:00 Michael Uvarov <notifications@github.com>:

**Pull request merged**
